version: '3.9'

services:
  # kioskapp:
  #   build: 
  #     context: ./kioskapp
  #     args:
  #       - AUTH_PROVIDER=localhost
  #       - AUTH_PROVIDER_PORT=8080
  #       - APP_HOST=kioskapp
  #       - APP_PORT=5000
  #   environment:
  #     - REACT_APP_AUTH_PROVIDER=localhost
  #     - REACT_APP_AUTH_PROVIDER_PORT=8080
  #     - REACT_APP_APP_HOST=kioskapp
  #     - REACT_APP_APP_PORT=5000
  #   depends_on:
  #     - api
  #   ports:
  #     - 5000:5000
  # api:
  #   build: ./api
  #   depends_on:
  #     database:
  #       condition: service_healthy
  #       restart: true
  #     keycloak:
  #       condition: service_started
  #   environment:
  #     - DB_HOST=database
  #     - AUTH_PROVIDER=keycloak
  #     - AUTH_PROVIDER_PORT=8080
  #   ports:
  #     - 3000:3000
  
  database:
    image: neo4j:4.0  
    environment:
      - NEO4J_AUTH=none
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc"]
    restart: always
    volumes:
      - ./neo4j/:/data
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 0s
    ports:
      - 7474:7474
      - 7687:7687

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    entrypoint: /opt/keycloak/bin/kc.sh start-dev
    volumes:
      - ./keycloak/:/opt/keycloak/data
    ports:
      - 8080:8080